### ISSUE TITLE
"captured" files for tests missing in archive at PyPI

### ISSUE THREAD

**Issue by htgoebel** [selectel/pyte#112]
The archive at PyPi is missing the `captured` files, thus tests will fail:
```
$ pip download --no-binary :all: pyte
$ tar xzf pyte-0.7.0.tar.gz
$ tree pyte-0.7.0/tests/
pyte-0.7.0/tests/
├── test_diff.py
├── test_history.py
├── test_input_output.py
├── test_screen.py
└── test_stream.py
```
Solution is simple: Add the directory to MANIFEST.in and upload a new archive to PyPI - maybe you need to increas the version, e.g. to `0.7.0p1`.

**Comment by superbobry** [comment]
Thanks, will do just that.
