### ISSUE TITLE
capture.py sample not using pyte

### ISSUE THREAD

**Issue by markfink** [selectel/pyte#114]
I am looking at your samples to get a better grasp on pyte. So far I am quite fond of it so thank you for sharing.

your capture.py sample contains the following line but does not do anything with it:

```python
    stream = pyte.Stream(pyte.Screen(80, 24))
```

...so I commented it out and it is still "working".

I figured that if I wanted to use pyte during capture I would use something like the following:

```python
    handle.write(stream.feed(data).display())
```

this gives me the following error:
TypeError: cannot use a string pattern on a bytes-like object

**Comment by superbobry** [comment]
The purpose of `capture.py` is to capture the "raw" output of a terminal app. I think the line you've spotted is some leftover debugging code, I've removed it in the `master` version. Thanks for reporting!

The captured sessions are used in the [`test_input_output`](https://github.com/selectel/pyte/blob/master/tests/test_input_output.py#L17).
