### ISSUE TITLE
echo -e '\e[12$p'

### ISSUE THREAD

**Issue by jonathanslenders** [selectel/pyte#117]
The above escape sequence doesn't seem to work correctly. I'm not sure what it means, but this will display a "p", while it should not display anything.

Tested with Pyte 0.8.0.
This escape sequence is generated by Vim 8.1.26 when loading.

FYI: I'm working again on pymux, converting it to prompt_toolkit 2.0. Thanks again for Pyte!

**Comment by superbobry** [comment]
Thanks for the report @jonathanslenders! This seems to be an XTerm sequence

```
CSI Ps $ p
          Request ANSI mode (DECRQM).  For VT300 and up, reply DECRPM is
            CSI Ps; Pm$ y
          where Ps is the mode number as in SM/RM, and Pm is the mode
          value:
            0 - not recognized
            1 - set
            2 - reset
            3 - permanently set
            4 - permanently reset
```
