### ISSUE TITLE
Write some command to bash and get its result

### ISSUE THREAD

**Issue by Alexey-T** [selectel/pyte#133]
Example nanoterm shows how to get output of e.g. bash.
now I need to put some string to bash- as a command- e.g. "ls". and get bash output for "ls".
how?

**Comment by superbobry** [comment]
Hey Alexey, [`webterm.py`](https://github.com/selectel/pyte/blob/master/examples/webterm.py) does that. It could be a bit hard to comprehend so if you are still unsure after giving it a go, please followup on StackOverflow. The issue tracker is not the best place to ask these kind of questions.
