### ISSUE TITLE
Docs are blurry here

### ISSUE THREAD

**Issue by Alexey-T** [selectel/pyte#134]
set_margins(top=None, bottom=None)[source]
Select top and bottom margins for the scrolling region.

Parameters:	
top (int) – the smallest line number that is scrolled.
bottom (int) – the biggest line number that is scrolled.

=====
Very blurry text. I don't get by text, what is the margin? Maybe the number1 is the minimal scroll position (for scroll cmds) and number2 is maximal?

Need new text, pls

**Comment by superbobry** [comment]
Hey Alexey, this method implements the DECSTBM CSI sequence, see e.g. [here](https://unix.stackexchange.com/questions/169509/how-to-use-esc-sequences-to-make-terminal-region-scrollable) and [here](https://terminalguide.namepad.de/seq/csi_sr/). I'd welcome a PR with better wording ;)
