### ISSUE TITLE
Need example like webterm but working only locally

### ISSUE THREAD

**Issue by Alexey-T** [selectel/pyte#135]
For CudaText plugin I want to use Pyte to run Bash process and catch its output into CudaText panel-editor.
CudaText plugin has input field which text I must put to Bash.

I cannot make example to test. (No XP with asyncio and Pyte).
webterm example is using HTTP and asyncio http, but I need an example which works in pure Linux terminal.
so I can run in terminal - "python3 nnnnn.py" and

- it runs Bash and Bash output is shown in some window (eg original terminal)
- I somehow enter commands to running bash, eg "ls"

**Comment by superbobry** [comment]
I'm sorry, I'm not able to provide examples on demand. Feel free to ask a more specific question on StackOverflow.
