### ISSUE TITLE
0.8.0 bdist removed from pypi?

### ISSUE THREAD

**Issue by MrMino** [selectel/pyte#143]
Looks like there's no wheel for pyte 0.8.0 on global PyPI. 

There is one for 0.7.0, but not for 0.8.0, and my archival CI runs show that just a few months ago there was no bdist building being done for pyte, which leads me to believe that whl for 0.8.0 has been removed. If so, do you have any idea who did it and why?

Not a big deal for me, I'm asking out of caution.

See https://pypi.org/simple/pyte/

**Comment by MrMino** [comment]
This hit me again today after switching between hosted PyPI repositories. Can you please rebuild `pyte-0.8.0-*-*-*.whl`?

**Comment by eldipa** [comment]
@MrMino This is probably a too late response but it is for future references. As far as I know, PyPI does not allow the publishers of a package to remove a package from PyPI to prevent breaking downstream users. At best, the publishers can `yank` a given version to prevent further usage.

**Comment by MrMino** [comment]
@eldipa are you sure? https://stackoverflow.com/questions/20403387/how-to-remove-a-package-from-pypi

**Comment by eldipa** [comment]
@MrMino you are absolutely, I really thought that you can only `yank` a version on PyPI but the option for `delete` it is there. My apologies.

**Comment by eldipa** [comment]
@superbobry sorry to bother you, could be possible to resubmit to PyPI the `0.8.0` version? I know that it is already `0.8.1` out there but I have some users with a dependency pinned to `0.8.0` and they let me know that randomly they cannot install `0.8.0` from PyPI.

No sure where is the problem, not even if a resubmission to PyPI could fix it.

**Comment by superbobry** [comment]
Thanks for the heads up. I think I might've forgotten to upload the wheel back then. The wheel is on PyPI now: https://pypi.org/project/pyte/0.8.0/#files.
