### ISSUE TITLE
move ansi escape parser to outta.parser module

### ISSUE THREAD

**Issue by milahu** [selectel/pyte#152]
i suggest we move the ansi parser to https://github.com/abingham/outta

see [def _parser_fsm](https://github.com/selectel/pyte/blob/fa5255a2d81e4ad16b0eeaf97636194c47e98ce1/pyte/streams.py#L210) and [def feed](https://github.com/selectel/pyte/blob/fa5255a2d81e4ad16b0eeaf97636194c47e98ce1/pyte/streams.py#L171)  in `pyte/streams.py`
these are similar to [def _parser_fsm](https://github.com/abingham/outta/blob/0458723dd5012102ef7ea12cbb5c4d47e85ded39/source/outta/parser.py#L184) and [def feed](https://github.com/abingham/outta/blob/0458723dd5012102ef7ea12cbb5c4d47e85ded39/source/outta/parser.py#L134) in `outta/parser.py`

the question is ... is the parser alone useful enough to justify a separete module?
i guess the answer is no. in that case, `outta` should be deprecated in favor of `pyte`

**Comment by abingham** [comment]
See also #147 where I make roughly the same proposal.
