### ISSUE TITLE
Publish a release

### ISSUE THREAD

**Issue by arcanis** [selectel/pyte#153]
I noticed Pyte was producing the wrong output for AIXTERM colors, by incorrectly setting the bold flag. As I was about to open a PR, I noticed it had already been fixed in master: https://github.com/selectel/pyte/commit/4672869d175cea2f80d124f6153fdcc62b53692b

Any chance a release could be published?

**Comment by superbobry** [comment]
Done in 7c8e2b9625eefd7bf28aef254b05a6b7c1bb2003.
