### ISSUE TITLE
[Question] Is pyte development still active?

### ISSUE THREAD

**Issue by matkuki** [selectel/pyte#164]
Hi,

I see a lot of `PR`'s and issues still open, is `pyte` development still active?
Or is there perhaps a fork with more up to date development?

Thanks

**Comment by superbobry** [comment]
Hi @matkuki,

I think `pyte` is more or less feature complete at this point, so there is no active development. I am not aware of any forks with a different dynamics.

I do sometimes go through bugs and PRs, but as you can see, that doesn't happen very often. Smaller PRs are easier to reviews, so they have a higher chance of being merged quickly.

**Comment by matkuki** [comment]
@superbobry 
Thank you for the detailed answer 👍👍👍
