### ISSUE TITLE
[Question] How to implement a scrollbar?

### ISSUE THREAD

**Issue by matkuki** [selectel/pyte#165]
Hi,

Is there a way to get information of a `HistoryScreen` to get:
- first line index
- last line index

and a way to set the currently visible first line in the screen?
I only found the `HistoryScreen.position` and the `prev_page` / `next_page` methods.

**Comment by mumu-lhl** [comment]
You can refer to [QTerminalScreen](https://github.com/mumu-lhl/eaf-pyqterminal/blob/bc4d9d778749b44028b98dc1689f2daae2cf4f41/eaf_pyqterm_term.py#L36) of EAF PyQterminal. It implements the scrollbar.

**Comment by matkuki** [comment]
Ah, excellent thanks 👍
