### ISSUE TITLE
Color information loss with `nano`?

### ISSUE THREAD

**Issue by matkuki** [selectel/pyte#167]
Hi

I'm using `Pyte` to create a terminal emulator and most things work without problems,
but when running the `nano` editor, the color information seems to be lost.
This is a screenshot of running `nano` with `Pyte`:
![image](https://github.com/selectel/pyte/assets/10289651/cb624f4f-5eb7-42c6-ae9f-d57b425e4536)
... but it should look like this (this is example of running `nano` in a default terminal):
![image](https://github.com/selectel/pyte/assets/10289651/55b11a2d-678d-4782-bb34-6ead9abb4ef4)

To test that my color handling is working I ran the 256 color test and I get this:
![image](https://github.com/selectel/pyte/assets/10289651/aefb3d5b-c346-478d-a59c-7cc04edeb30a)
... so the color handling is correct.

Any ideas on how to fix this?

**Comment by matkuki** [comment]
@superbobry
I've also checked that there is no color information in the buffer,
so when printing the `bg` and `fg` of each character, it's always `default` for both for all characters in the buffer,
when the `nano` screen is loaded.

**Comment by mumu-lhl** [comment]
When `reverse` is True, you need to swap the default color ​​​​of `fg` and `bg`.

**Comment by matkuki** [comment]
@mumu-lhl 
Yes, that's it, thanks 👍
