### ISSUE TITLE
Handling of backspace/delete

### ISSUE THREAD

**Issue by joushou** [selectel/pyte#25]
After some testing, I have noticed that handling of backspace/delete in Stream does not seem to be perfect.

My terminal emulators generally support these 4 options for backspace and delete:
- CTRL-H - \x08
- ASCII DEL - \x7f
- ESCAPE - \x1b[3~ 
- TTY ERASE - becomes ASCII DEL

Many terminals only have settings to go from ASCII DEL to CTRL-H for compatibility reasons. This option makes Emacs sad, but is sometimes required. The escape sequence appears to be the only sequence resulting in forward-delete behaviour in my shell (Although it appears broken when I ssh through tmux). Neither the ASCII del char, nor the escape sequence is handled by pyte's streams. The del char never seems to raise any events, with the escape sequence raising a debug event.

I will most likely fork it later today to add DEL to control and escape and submit a pull request, unless I forget or someone else manage to do it before me.

_UPDATE_:
The issue lies with ASCII DEL (\x7f) being explicitly ignored. The forward delete thing is under another issue, and closed for now. As per a comment from @superbobry this was likely to fix Midnight Commander, but I believe that it might be due to incorrect handling. \x7f is just a whitespace rendition-wise, cursor-increment and all. It's only magic when it arrives on stdin from a terminal emulator, which it tends to do quite often.

**Comment by superbobry** [comment]
I've just tested the following in iTerm2, xterm and `pyte` (via `webterm.py`)

```
$ awk 'BEGIN{printf "foobar%c42\n", 127}'
```

iTerm2 produces `foobar 42`, while xterm and `pyte` both result in `foobar42`. I would rather stick with xterm on that, because iTerm doesn't pass "Cursor movement" vttest.

Please feel free to reopen if you think this behaviour is incorrect.
