### ISSUE TITLE
DiffScreen.draw() marks wrong line as dirty when wrapping occurs

### ISSUE THREAD

**Issue by dcoshea** [selectel/pyte#36]
The current implementation of `DiffScreen.draw()` in `pyte/screens.py` as at 12276a8 is that it first marks the row containing the cursor as dirty and then calls `Screen.draw()`.

However, the latter method will, if wrapping is enabled (`if mo.DECAWM in self.mode`), move to the next line before actually writing the character to the virtual terminal.  This means that the wrong line might have been marked as dirty.

It seems to me that simply switching the order of the statements in `DiffScreen.draw()` would fix this issue.

**Comment by superbobry** [comment]
Thank you for reporting this. It seems that with wrapping enable the dirty line would indeed by `y + 1` and not `y`. Do you mind submitting a PR with a unit-test for this case?

**Comment by dcoshea** [comment]
Sure, thanks!

**Comment by dcoshea** [comment]
I submitted pull request #38, hope it's ok :)
