### ISSUE TITLE
(FYI) pymux

### ISSUE THREAD

**Issue by jonathanslenders** [selectel/pyte#41]
Hi all,

Thanks a lot for making Pyte! It allowed me to create pymux: https://github.com/jonathanslenders/pymux

There are a few changes I had to do to the "stream" class. For some of them, I think it make sense to merge them back into Pyte. Please, have a look to this file:
https://github.com/jonathanslenders/pymux/blob/master/pymux/stream.py
I needed support for CPR, device attributes, and terminal title support. Further, the ``hasattr`` calls in "dispatch" were not acceptable.

Probably, in the future, I'll do some more changes in order to improve the performance. Let me know whether you're interested.

The screen class is completely custom made: https://github.com/jonathanslenders/pymux/blob/master/pymux/screen.py

Jonathan

**Comment by superbobry** [comment]
Hi Jonathan, `pymux` looks great!

> I needed support for CPR, device attributes, and terminal title support. 

Cool! We've thought about adding these at some point, but they weren't needed for our web-terminal use case.

> Further, the hasattr calls in "dispatch" were not acceptable.

Do you mean they turned out to be too expensive? My guess is that if you're after speed the loop and branching conditions in `Stream` can be optimized by Cython.

> Probably, in the future, I'll do some more changes in order to improve the performance. Let me know whether you're interested.

Yes, very interested.

**Comment by jonathanslenders** [comment]
Hi @superbobry,

Yesterday evening, I rewrote half of my ``stream`` class and ended up with this: https://github.com/jonathanslenders/pymux/blob/master/pymux/stream.py#L56

The result is about 10x faster. (Pymux as a whole became at least 3x faster because of this.)

The problem with the original code is that many things happen for every single character that we receive from the process. Normally, in Python we don't like to do string manipulations at the character level, because that is slow. So, if we have to do, we have to make this part very efficient.

- There was a feed and a consume function. This doesn't make sense because every external call to "consume" could as well have gone to "feed". So better place the for-loop in-line and don't do type checking twice.
- The lookup in ``self.handlers`` is expensive. Way too expensive to do for every single character. Better than setting a ``self.state`` string, would be to set a ``self.current_handler`` callable.
- Actually all attribute lookups are expensive. (The ``.`` operator is expensive.) Use the "dis" module to analyse.
- ``getattr`` and ``hasattr`` are slow.
- I didn't need multiple listeners, so I optimized my code to have just one listener.

What I did was putting all the state in a coroutine, a generator that I feed one character at a time. All variables that are used are locals in that function, so the lookup will be very fast. Calls to dispatch are optimized. ``dispatch`` is even avoided when we can call the function directly. Further, we don't handle any exceptions. Thanks to defaultdict, we can't have exceptions in this coroutine itself, and we won't hide exceptions from the stream class. The function is organized in a way that we don't need the calls to ``reset``. (Everything that ``reset`` did was setting variables that are know initialized at the right point in the coroutine.)

I know that this function is longer. But it's manageable, and IMHO worth it, because of the performance benefit.

I'm not sure when I will have time to create pull requests for Pyte, but feel free to copy the useful parts.
Jonathan

**Comment by superbobry** [comment]
Hi Jonathan, thank you, I'll see if I can merge some of your changes into `pyte`.

> The result is about 10x faster. (Pymux as a whole became at least 3x faster because of this.)

I wonder how did you benchmark it? Do you have sample scripts somewhere?

**Comment by jonathanslenders** [comment]
The duration of executing ``time find /etc`` in pymux became about 3x faster after my patch. Further, I use runsnakerun to profile the code and find the bottlenecks, and measure the time spent in all parts of the code.

(Feel free to not merge it, if you don't like it. It's not the most beautiful piece of code, but given that it's a small piece and a painful bottleneck, I went as far as I could, optimizing it without C/Cython.)

**Comment by superbobry** [comment]
Thank you very much, I've incorporated both the speed improvements in `Stream` and CSR/CPR support. Please do let me know if you spot more bottlenecks.
