### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tony** [selectel/pyte#42]
Thank you for this library! I'm using with https://github.com/wraithan/pytmux.

I assume it's your intention by making this LGPL to simply give pyte-related contributions back to the project. Most python projects are permissively licensed (ISC, MIT, BSD, Apache) since it's not a practice distribute binary blobs. The language used in LGPL however doesn't protect edge cases that exist in interpreted scripting languages, like subclassing, monkey-patching, mixing in, vendorizing (copying the code into a project), copying and pasting snippets.

If you could put it under MIT/BSD/Apache that would be a lot nicer downstream.

**Comment by superbobry** [comment]
Hi Tony. I'm all for BSD-style permissive licenses, but in the case of `pyte` the choice of the license was not mine, but my employers. 

I'm not sure if there's a chance of relicense, @ad, what do you say?

**Comment by petervaro** [comment]
@superbobry IMHO if I were you, I would only switch from `LGPL` to `GPL` (most likely v3). It is the best license if you are concerned about the act of sharing of your code and the ownership on it, as it is a strong *copyleft license that requires anyone who distributes your code or a derivative work to make the source available under the same terms, and also provides an express grant of patent rights from contributors to users.*<sup>1</sup>

It is not true, that *most* projects are under these simpler licenses, as a matter of fact, all the great and successful FOSS ones are under `GPL` (mostly v2 for historical reasons).

<sup>1</sup> [Choose an open source license](https://choosealicense.com)

**Comment by tony** [comment]
This issue can be closed as I worked around the license issue my not using inline editing on the project I had.

> It is not true, that most projects are under these simpler licenses, as a matter of fact, all the great and successful FOSS ones are under GPL (mostly v2 for historical reasons).

For Python?

Not even close in 2017. https://pypi.python.org/pypi?%3Aaction=browse, see License :: OSI Approved.

I don't even care about popularity. I can't have viral clauses in code I use. It's not my choice I can't use the license, the lawyers say no go.
