### ISSUE TITLE
pyte is not support vim file?

### ISSUE THREAD

**Issue by wcc526** [selectel/pyte#45]
pyte is not support vim file?

When I run vi XXX.file ,pyte does not work.

**Comment by superbobry** [comment]
Could you please attach a fragment of your code so I can reproduce the issue?

**Comment by wcc526** [comment]
The reference in here.
https://github.com/atagar/ReviewBoard/blob/71de26348ad16089e5fc4e5cc3fa9b445065fd5f/reviewboard/cmdline/rbssh.py

My basic code is 

     def __init__(self):
            stream = pyte.DebugStream()
            screen = pyte.Screen(80, 24)
            stream.attach(screen)

    def process_channel(self, channel):
        if channel.closed:
            return False

        if channel.recv_ready():
            data = channel.recv(4096)
            stream.feed(data)

            for line in screen.display:
                 LOG.info(line)


            if not data:
                logging.debug('!! stdout empty\n')
                return False

            sys.stdout.write(data)
            sys.stdout.flush()


I use pyte as library for the ssh command.It is user for ssh command audit in the bastion host.My purpose is log all the user's input ssh command.

The example is https://www.sshtools.com/en/content
The ssh gateway.

**Comment by superbobry** [comment]
Do you mean that running `vi 1.txt` produces an empty screen? Can you attach `LOG.info` output?

**Comment by wcc526** [comment]
https://github.com/wcc526/bastion-ssh

The complete code is in here.

You can run BastionSSH.py to connect remote linux server.It will use your local private key.and the command will be log.

def command_line_runner():
    context = Context()
    context.hostname = "10.121.77.16"
    context.username = "vagrant"
    context.user = getpass.getuser()
    context.port = 22
    audit_cmd = AuditCMD(context)
    bastioncmd = BastionCmd(context)
    bastioncmd.do_ssh(audit_cmd)

**Comment by superbobry** [comment]
Your code seems to hang if I replace `DebugStream` with `Stream`.

**Comment by wcc526** [comment]
def audit_channel(self, x):
    	self.stream.feed(x)
        for line in self.screen.display:
             LOG.info(line)

     def process_stdin(self, channel):
        """Read data from stdin and send it over the channel."""
        try:
            buf = os.read(self.input.fileno(), 1)
        except OSError:
            buf = None
        if not buf:
            return False
        channel.send(buf)
        # add filter
        self.audit_cmd.audit_stdin(buf)
        return True

I don't know why  hang if replace DebugStream with Stream.x is from sys.stdin.

**Comment by wcc526** [comment]
The problem has been solved in this commit.

The problem has been solved in your latest commit.

https://github.com/selectel/pyte/commit/4b498c09b3df14db437ea58121b0714c0930b910.

Please close this issue.
