### ISSUE TITLE
Argument error running examples

### ISSUE THREAD

**Issue by BrendanSimon** [selectel/pyte#51]
How do you run the examples?  I keep getting an argument error.

```
$ python2.7 pyte-example-hello.py 
screen = Screen(80, 24)
Traceback (most recent call last):
  File "pyte-example-hello.py", line 20, in <module>
    stream = pyte.Stream(screen)
TypeError: __init__() takes exactly 1 argument (2 given)
```

```
$ python2 pyte-example-nanoterm.py ls
Traceback (most recent call last):
  File "pyte-example-nanoterm.py", line 30, in <module>
    stream = pyte.Stream(screen)
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by superbobry** [comment]
Hi Brendan, you might be running examples from `master` using a stable version of `pyte`. Try checking out the latest stable release

```bash
$ git checkout 0.5.2
```

or [download them](https://github.com/selectel/pyte/tree/0.5.2/examples) via GitHub.

**Comment by BrendanSimon** [comment]
I installed `pyte` (v0.5.2) via `pip`

```
$ pip freeze | grep pyte
pyte==0.5.2
```
Do you mean install via `git checkout master` ???

**Comment by BrendanSimon** [comment]
Maybe I misunderstood.  Do you mean check 0.5.2 and use the examples in that.  I guess so :)

**Comment by superbobry** [comment]
Yeah, apologies if I was a bit unclear. 

The examples are updated along with `pyte`, so if you're using 0.5.2 you need to download or checkout the 0.5.2 version of examples.
