### ISSUE TITLE
display Chinese characters

### ISSUE THREAD

**Issue by paramoecium** [selectel/pyte#52]
When I feed strings with Chinese characters to the stream as the following:

```python
import pyte
screen = pyte.Screen(10, 4)
stream = pyte.Stream()
stream.attach(screen)
stream.feed("你好嗎")
lines = screen.display
for idx, line in enumerate(screen.display, 1):
    print("{0:2d} {1} ¶".format(idx, line))
```

It shows this on my terminal:

![image](https://cloud.githubusercontent.com/assets/7474793/17060804/47442da6-505e-11e6-9122-31684358acbb.png)

How can I eliminate the spaces between 你 好 嗎?

**Comment by superbobry** [comment]
Which version of `pyte` are you using?

**Comment by shaform** [comment]
I get the same spaces with pyte 0.5.2 on python2.7.

**Comment by superbobry** [comment]
Very interesting. I'll look into this, thank you!

**Comment by superbobry** [comment]
I've managed to track down the issue: `Screen.display` ignored character width.

Please try the `master` version and let me know if it worked for you (it should :).
