### ISSUE TITLE
Update the pyte distributed through pip

### ISSUE THREAD

**Issue by hei5enberg** [selectel/pyte#53]
The pip version of pyte giving error.(0.5.2)
stream = pyte.Stream(screen)
TypeError: __init__() takes exactly 1 argument (2 given)

The repository version is working fine(0.6.0). Please update the pyte in pip.

**Comment by superbobry** [comment]
My guess is that you're running examples from the `master` version using `pyte` 0.5.2. See #51.

**Comment by hei5enberg** [comment]
yeah, that's the case. 
Anyway everything working fine. But if you could update the pip version, that would be great!!

**Comment by superbobry** [comment]
Yeah, I'll do that as soon as I get a free weekend to finish backporting stuff from `pymux`.

Closing this issue.
