### ISSUE TITLE
TypeError: __init__() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by yonghuming** [selectel/pyte#58]
Traceback (most recent call last):
  File "D:\coding\pty\pty.py", line 19, in <module>
    stream = pyte.Stream(screen)
TypeError: __init__() takes exactly 1 argument (2 given)
[Finished in 0.1s]

**Comment by demiurg906** [comment]
try that:
stream = pyte.Stream()
stream.attach(screen)

**Comment by superbobry** [comment]
@demiurg906 thanks!

@yonghuming we've [changed](/selectel/pyte/blob/master/CHANGES) the API quite a bit in the `master` version. If you're using the latest stable version, please take a look at 0.5.2 [examples](https://github.com/selectel/pyte/tree/0.5.2/examples) and [docs](http://pyte.readthedocs.io/en/0.5.2/).
