### ISSUE TITLE
UTF-8 character incorrectly interpreted as OSC

### ISSUE THREAD

**Issue by tspivey** [selectel/pyte#62]
When trying to upgrade my project to use the current git master, I needed to send data as bytes.
This works, however I can't decode UTF-8 data. For example, the following test script will fail:
```
import pyte
screen = pyte.Screen(10, 1)
stream = pyte.Stream(screen)
c = b"\xE2\x80\x9D" #u+201d
stream.feed(c)
print(screen.display)
```
The first character of the screen should be '”', but is blank.

It looks like pyte is interpreting the 9d as OSC, causing problems from there.
According to Wikipedia articles on [ANSI escape codes][1] and [C0 and C1 control codes][2], in UTF-8 mode, OSC (also ST, CSI) should be encoded in UTF-8, so in this case 0xc2 0x9d.

[1]: https://en.wikipedia.org/wiki/ANSI_escape_code#Sequence_elements
[2]: https://en.wikipedia.org/wiki/C0_and_C1_control_codes

**Comment by superbobry** [comment]
Hi Tyler, thanks for reporting this inconsistency. I've briefly looked through the Wikipedia pages and haven't found any mentions of the behaviour you're describing. Could you please quote a relevant passage?

**Comment by tspivey** [comment]
From ANSI escape code:
> In 8-bit environments, these two character sequences can be merged into single byte, using the 0x80–0x9F control character range.[13]:5.3.b Devices that support just ASCII (7-bit bytes) recognize only the two-character sequence. The same is true for devices that support 8-bit bytes but use the 0x80–0x9F control character range for other purposes. On terminals that use UTF-8 encoding, both forms take 2 bytes (CSI in UTF-8 is 0xC2, 0x9B)[discuss] but the ESC[ sequence is clearer.


And from C0 and C1 control codes:
> Unicode sets aside 65 code points for compatibility with ISO/IEC 2022. The Unicode control characters cover U+0000—U+001F (C0 controls), U+007F (delete), and U+0080—U+009F (C1 controls). Unicode only specifies semantics for U+001C—U+001F, U+0009—U+000D, and U+0085. The rest of the control characters are transparent to Unicode and their meanings are left to higher-level protocols. The C1 characters in Unicode require 2 bytes to be encoded in UTF-8 (for instance CSI at U+009B is encoded as the bytes 0xC2, 0x9B in UTF-8). Thus the corresponding control functions are more commonly accessed using the equivalent two byte escape sequence intended for use with systems that have only 7-bit bytes.

**Comment by superbobry** [comment]
A straightforward way to fix this would be to add more branching to the already complicated `Stream._parser_fsm`, so I was thinking of tacklingthe issue differently: restrict `pyte` to UTF-8 only inputs. What do you think?

**Comment by superbobry** [comment]
A good reference on the topic: http://www.cl.cam.ac.uk/~mgk25/unicode.html#term picked up from iTerm2 source code.

**Comment by superbobry** [comment]
Okay, so the plan to approach this is:

1. Retain `bytes` as the input type to `pyte.Stream.feed`, but change `pyte.Screen.draw` back to UTF-8.
2. Move `use_utf8` and `utf8_encoder` back to `pyte.Stream`.
3. Ensure G0/G1 calls are ignored when UTF-8 is active. If UTF-8 is not active, assume ASCII and translate it using the active charset.
