### ISSUE TITLE
Behaviour of linefeed above scrolling region

### ISSUE THREAD

**Issue by tspivey** [selectel/pyte#63]
Assume the scrolling region is set from line 3 to 27 (VT-100 coordinates).
If I send CSI H to bring the cursor to 1, 1, then send a linefeed, I think the cursor should be at 2, 1.
However, it moves to 3, 1.

If I run the following in the shell, with screen:
```
clear;echo -ne '\x1b[3;27r\x1b[H\n';read
```
Then press CTRL-A i to check the cursor position, it shows column 2, line 1 as I expected.

However, the same sequence with pyte:
```
stream.feed(b'\x1b[3;27r\x1b[H\n')
print(screen.cursor.y, screen.cursor.x)
```
returns (2, 0) -- line 3 column 1 accounting for the 0-based offsets.

I'm not sure who's correct here, except it looks like this is corrupting my nano display if I run ssh -> screen -> nano.

**Comment by superbobry** [comment]
That's a tricky one!

I've failed to find the expected behaviour in VT100, VT220 and VT520 manuals, however, Terminal.app, iTerm3, tmux and Linux terminal all consistently ignore the top margin when doing a linefeed. Therefore, I think it makes sense for pyte to mimic that.
