### ISSUE TITLE
Reply to the Cursor-Position-Report sequence

### ISSUE THREAD

**Issue by jquast** [selectel/pyte#71]
pyte should respond to the "Cursor Position Report" sequence:

- http://vt100.net/docs/vt510-rm/CPR.html

An application prints capability `u6`, which terminal emulator discovers and replies in format of capability `u7`. For xterm, this is `'\x1b[6n'` and `'\x1b[%i%d;%dR'`, respectively. I implemented the "client side" of this in blessed, which contains many details about this sequence.

I intend to use this functionality and will contribute it if necessary as needed downstream for test case of https://github.com/jquast/blessed/issues/94

**Comment by superbobry** [comment]
``pyte`` [supports CPR](https://github.com/selectel/pyte/blob/0.5.2/pyte/screens.py#L887) since version 0.5.2. All you have to do is implement `Screen.write_process_input`.

**Comment by superbobry** [comment]
Closing for now. Feel free to reopen if you think CPR support is broken or could be improved.
