### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by hryamzik** [selectel/pyte#78]
At least the [helloworld](/selectel/pyte/blob/master/examples/helloworld.py) one.

```py
stream = pyte.Stream(screen)
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by superbobry** [comment]
I think you're running `master` examples with a stable version of `pyte`. Please refer to the corresponding [tag](https://github.com/selectel/pyte/tree/0.5.2/examples) on GitHub.

**Comment by hryamzik** [comment]
That works, thanks!
