### ISSUE TITLE
Konsole clear code missing

### ISSUE THREAD

**Issue by shaolo1** [selectel/pyte#80]
Under KDE bash clear returns [3J which causes 'interval not defined' error in erase_in_display(3).  Any chance of adding this?

see http://stackoverflow.com/questions/5367068/clear-a-terminal-screen-for-real/5367075#5367075

**Comment by superbobry** [comment]
What is the value of `TERM` env variable? VT220 does not support `[3J`, but `xterm` does (erase all saved lines). Would it be okay for you if this had been a noop in `pyte`?

**Comment by shaolo1** [comment]
Where would I see the TERM env variable?
Locally I patched erase_in_display() from "elif how == 2" to "elif how == 2 or how == 3"

**Comment by superbobry** [comment]
Hmm, you're right there is indeed a `[3J` in linux as well:

```
       The action of a CSI sequence is determined by its final character.

       J   ED        Erase display (default: from cursor to end of display).
                     ESC [ 1 J: erase from start to cursor.
                     ESC [ 2 J: erase whole display.
                     ESC [ 3 J: erase whole display including scroll-back
                                buffer (since Linux 3.0).
```

In `pyte` this affects both `Screen` and `HistoryScreen`.
