### ISSUE TITLE
0.6.0 release

### ISSUE THREAD

**Issue by uSpike** [selectel/pyte#82]
Hi,

I was just wondering if there was a time-line for releasing 0.6.0 (or the next version)?
The changes to streams are really beneficial to me for performance, especially on Raspberry Pis.  Feeding 100's of thousands of characters caused a big slow down, and the new changes are very nice!

Thanks, this project is great.

**Comment by superbobry** [comment]
Hi, thank you for the feedback. Raspberry Pi looks like a very intriguing use-case. Please do report the inefficiencies you encounter. 

I plan to release 0.6.0 in the end of May, once we finish the work on #76.

**Comment by uSpike** [comment]
Thanks for the update!  The pi seems to struggle the most with calls to `wcwidth` which seem to be taking up the majority of CPU time, but i'll continue tracing and let you know more details.

**Comment by superbobry** [comment]
Yep, @istarion spotted that 30% of the CPU time being spent in `wcwidth` as well. We will most likely address that before the release.

**Comment by superbobry** [comment]
I've released 0.6.0 with the new ``Screen`` and cached ``wcwidth``. Although caching is 3.X-only for now.
