### ISSUE TITLE
Handling of character set switching in UTF-8 mode

### ISSUE THREAD

**Issue by tspivey** [selectel/pyte#88]
With pyte 0.6.0, the following code just leaves a B on the terminal display:
```
import pyte
screen = pyte.Screen(80, 24)
stream = pyte.Stream()
stream.attach(screen)
stream.feed('\x1b(B')
print(screen.display[0].strip())
```

Reading the code (and the associated FAQ entry), it says that the escape sequence should be ignored.
The code ignores it by not reading the last character.

However, if I run lynx in my shell (TERM=xterm, LANG=en_US.UTF-8), this sequence is sent quite a bit, leaving B in my terminal.

**Comment by superbobry** [comment]
Hi Tyler. Thanks for the bug report, it should've been fixed in `master`. Could you give it a try and let me know if it works for you?

**Comment by tspivey** [comment]
It's working. Thanks for the fix.
