### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jonathanslenders** [selectel/pyte#97]
Hi there, just wondering whether there will be a new release soon?
I noticed that the latest Pyte release doesn't render htop correctly in my setup, but the latest commit from here works just fine.

(I'm working on a new prompt_toolkit terminal emulator, which builds on top of the prompt_toolkit 2.0 branch. It will be used in a future pymux version.)

Thanks!

**Comment by superbobry** [comment]
Hi Jonathan, prompt_toolkit terminal emulator sounds like a great idea! I will try to release over the weekend.

**Comment by superbobry** [comment]
Just pushed 0.7.0 to PyPI.
